Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -35,6 +35,19 @@ jobs:
       run: ls -l
 
     - name: Upload model to Hugging Face
+    - name: Run Training Script
+  run: python train.py
+
+    - name: Verify model file exists
+  run: |
+    echo "Checking model file..."
+    ls -l
+    test -f model.pkl && echo "MODEL EXISTS" || echo "MODEL MISSING "
+
+    - name: Upload model to Hugging Face
+  env:
+    HF_TOKEN: ${{ secrets.HF_TOKEN }}
+  run: python upload_model.py
       env:
         HF_TOKEN: ${{ secrets.HF_TOKEN }}
       run: python upload_model.py
